# Generated by Django 4.2.19 on 2025-05-17 18:35

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('hidden_user', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': [('base_permission', 'All basic permissions of a user'), ('admin_permission', 'All basic permissions of an admin')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('content', models.TextField(verbose_name='Message')),
                ('pud_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('is_read', models.BooleanField(default=False, verbose_name='Seen')),
                ('message_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('connected_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.chat')),
                ('sender', models.ForeignKey(null=True, on_delete=models.SET(home.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Multichat',
            fields=[
                ('chat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.chat')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Choose chat members')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('home.chat',),
        ),
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('chat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.chat')),
                ('member1', models.ForeignKey(null=True, on_delete=models.SET(home.models.get_sentinel_user), related_name='companion', to=settings.AUTH_USER_MODEL, verbose_name='Choose a user')),
                ('member2', models.ForeignKey(null=True, on_delete=models.SET(home.models.get_sentinel_user), related_name='you', to=settings.AUTH_USER_MODEL, verbose_name='YOU')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('home.chat',),
        ),
    ]
