# Generated by Django 4.2.19 on 2025-03-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(default='default', max_length=80, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
