# Generated by Django 4.2.20 on 2025-05-01 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chat',
            new_name='connected_chat',
        ),
    ]
