# Generated by Django 4.2.19 on 2025-04-27 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialog',
            old_name='members',
            new_name='member1',
        ),
    ]
