# Generated by Django 4.2.19 on 2025-03-19 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.AutoField(default=0, editable=False, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('D', 'Dialog'), ('C', 'Chat')], default='D', max_length=1, verbose_name='Тип')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
                ('messages', models.ManyToManyField(to='home.message', verbose_name='Сообщение')),
            ],
        ),
    ]
