# Generated by Django 4.2.19 on 2025-05-08 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ouruser',
            options={'permissions': [('base_permission', 'All basic permissions of a user')]},
        ),
    ]
