# Generated by Django 4.2.19 on 2025-04-30 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_members_dialog_member1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chat',
            new_name='multichat',
        ),
    ]
