# Generated by Django 4.2.19 on 2025-05-08 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_ouruser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ouruser',
            options={'permissions': [('base_permission', 'All basic permissions of a user'), ('admin_permission', 'All basic permissions of an admin')]},
        ),
    ]
