# Generated by Django 4.2.19 on 2025-04-30 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_chat_message_multichat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='multichat',
            new_name='chat',
        ),
    ]
