# Generated by Django 4.2.19 on 2025-04-13 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_chat_type_alter_chat_members_alter_chat_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
    ]
