# Generated by Django 4.2.19 on 2025-04-30 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_message_dialog_alter_message_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='member2',
            field=models.ForeignKey(default='ann', on_delete=django.db.models.deletion.CASCADE, related_name='you', to=settings.AUTH_USER_MODEL, verbose_name='YOU'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dialog',
            name='member1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companion', to=settings.AUTH_USER_MODEL, verbose_name='Choose a user'),
        ),
    ]
