# Generated by Django 4.2.19 on 2025-04-16 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_message_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.chat'),
        ),
        migrations.DeleteModel(
            name='Dialog',
        ),
    ]
