# Generated by Django 4.2.19 on 2025-04-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_dialog_member2_alter_dialog_member1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
