# Generated by Django 4.2.19 on 2025-04-30 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('home', '0007_alter_dialog_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialog',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='multichat',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='dialog',
            name='id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='dialog',
        ),
        migrations.RemoveField(
            model_name='multichat',
            name='id',
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddField(
            model_name='dialog',
            name='chat_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.chat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multichat',
            name='chat_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.chat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.chat'),
        ),
    ]
