# Generated by Django 4.2.19 on 2025-04-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_message_chat_delete_dialog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(max_length=80, verbose_name='name'),
        ),
    ]
