# Generated by Django 4.2.19 on 2025-04-17 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_chat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='companion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companions', to=settings.AUTH_USER_MODEL, verbose_name='companion'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(related_name='member', to=settings.AUTH_USER_MODEL, verbose_name='Choose chat members'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('D', 'Dialog'), ('C', 'Chat')], default='C', max_length=1, verbose_name='Тип'),
        ),
    ]
