# Generated by Django 4.2.19 on 2025-04-17 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_chat_companion_alter_chat_members_alter_chat_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='companion',
        ),
    ]
